name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install -y shellcheck gitleaks
      
      - name: shellcheck
        run: |
          find . -type f -name "*.sh" -exec shellcheck {} \;

      - name: gitleaks
        run: |
          gitleaks detect

      